name: Build Output
on:
  pull_request:
    types: [labeled]

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build-output:
    name: Build output
    runs-on: macos-15
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'build output' }}
    steps:
      - name: Remove 'build output' label
        if: ${{ github.event.action == 'labeled' }}
        run: |
              curl \
              -X DELETE \
              -H 'Accept: application/vnd.github.v3+json' \
              -H 'Authorization: token ${{ github.token }}' \
              'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/build%20output'
      
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Get Swift version
        run: swift --version
        
      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_26.0.app/Contents/Developer'
     
      - name: Build Swift package
        run: swift build --configuration release
     
      - name: Build Ignite site
        run: .build/release/Docs
      
      - name: Push changes to the Build folder
        run: |
          git config --global user.name "Buildbot"
          git config --global user.email "buildbot@users.noreply.github.com"
          git add Build/*
          git commit -m "[BOT] build output for ${{ github.event.number }}"
          git push origin HEAD:${{ github.head_ref }} --force
